close all
clear all
clc

Subject = 'Giuseppe';
Task = 'Tazzina';

data = load(['datasets/' Task '.dat']);
IDS_Definition
MkSuppDimensions = [7 15]; %MkSuppDimensions = [15 7] = [Suppx Suppy]

dataset_reorg_UpperLimb_NoPlots
%MKPos=MKPosSmoothed;

[NumFrame,~] = size(MKPos); 

load (['EstimatedAngles/EstimatedQArm' Subject Task '.mat'])
load (['EstimatedParameters/UpperLimbParametersDEF' Subject '.mat'])

figure;
for i =100%1:NumFrame
    
    clf;hold on;


    AnglesNow = EstimatedQ(:,i);%*0 + [0 0 0 0 0 0 0]';
    MeasuresNow = MKPos(i,:)'; %column vector 48 elem
    EstimationsNow = hfun([UpperLimbParametersDEF 15 7], AnglesNow); %column vector 36 elem


    %%%%%%%%%%%%%%%%%%%%%% Reference Sys Plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     plot3([0 30],[0 0],[0 0],'r','LineWidth',2)
%     plot3([0 0],[0 30],[0 0],'g','LineWidth',2)
%     plot3([0 0],[0 0],[0 30],'b','LineWidth',2)
%     
    %%%%%%%%%%%%%%%% Estimated Positions of Joints %%%%%%%%%%%%%%%%%%%%%%%%
    TShoulder = gWorldS1fun([UpperLimbParametersDEF 15 7], AnglesNow);
    DistWorldShoulder = TShoulder(1:3,4);
    TElbow = gWorldE1fun([UpperLimbParametersDEF 15 7], AnglesNow);
    DistWorldElbow = TElbow(1:3,4);
    TElbow = gWorldE1fun([UpperLimbParametersDEF 15 7], AnglesNow);
    DistWorldElbow = TElbow(1:3,4);
    TWrist = gWorldW1fun([UpperLimbParametersDEF 15 7], AnglesNow);
    DistWorldWrist = TWrist(1:3,4);
    THand = gWorldHfun([UpperLimbParametersDEF 15 7], AnglesNow);
    DistWorldHand = THand(1:3,4);
    %%%%%%%%%%%%%%%%%%% Star Positions (ESTIMED) %%%%%%%%%%%%%%%%%%%%%%%%%%
    r     = 43;   %lunghezza stanghette 
    Gamma = pi/6; %Angolo fra le stanghette 
    hMK1  = 45;   %quota led terzo piano
    hMK2  = 40;   %quota led secondo piano
    hMK3  = 35;   %quota led primo piano
    hMK4  = 67;   %quota led piano alto == lunghezza lato corto
    d1    = 5;    %lunghezza collo del led pi? alto (cappuccio)

    StarLocalCoords = [r*cos(Gamma) r*sin(Gamma)  hMK1;... %MK1
                       r            0             hMK2;... %MK2
                       r*cos(Gamma) -r*sin(Gamma) hMK3;... %MK3
                       0            0             hMK4];   %MK4
                   
%     plot3([StarLocalCoords(1,1) StarLocalCoords(2,1) StarLocalCoords(3,1) StarLocalCoords(4,1)],...
%           [StarLocalCoords(1,2) StarLocalCoords(2,2) StarLocalCoords(3,2) StarLocalCoords(4,2)],...
%           [StarLocalCoords(1,3) StarLocalCoords(2,3) StarLocalCoords(3,3) StarLocalCoords(4,3)],'kd','LineWidth',2)

    MeasuresNow = [StarLocalCoords(1,:)'; StarLocalCoords(2,:)'; StarLocalCoords(3,:)'; StarLocalCoords(4,:)'; MeasuresNow];  
    %%%%%%%%%%%%%%%%%%% Star Positions (MEASURED) %%%%%%%%%%%%%%%%%%%%%%%%%
%     plot3([MeasuresNow(1) MeasuresNow(4) MeasuresNow(7) MeasuresNow(10)],...
%           [MeasuresNow(2) MeasuresNow(5) MeasuresNow(8) MeasuresNow(11)],...
%           [MeasuresNow(3) MeasuresNow(6) MeasuresNow(9) MeasuresNow(12)],'r*','LineWidth',2)

    %%%%%%%%%%%%%% MEASURED Positions of Markers ARM %%%%%%%%%%%%%%%%%%%%%%
    plot3([MeasuresNow(13)],...
          [MeasuresNow(14)],...
          [MeasuresNow(15)],'r*','LineWidth',2)
    plot3([MeasuresNow(16)],...
          [MeasuresNow(17)],...
          [MeasuresNow(18)],'g*','LineWidth',2)
    plot3([MeasuresNow(19)],...
          [MeasuresNow(20)],...
          [MeasuresNow(21)],'b*','LineWidth',2)
    plot3([MeasuresNow(22)],...
          [MeasuresNow(23)],...
          [MeasuresNow(24)],'k*','LineWidth',2)

    plot3([MeasuresNow(13) MeasuresNow(16) MeasuresNow(19) MeasuresNow(22) MeasuresNow(13)],...
          [MeasuresNow(14) MeasuresNow(17) MeasuresNow(20) MeasuresNow(23) MeasuresNow(14)],...
          [MeasuresNow(15) MeasuresNow(18) MeasuresNow(21) MeasuresNow(24) MeasuresNow(15)],'k-','LineWidth',2)
%     %%%%%%%%%%%% MEASURED Positions of Markers FOREARM %%%%%%%%%%%%%%%%%%%%
% %     plot3([MeasuresNow(25)],...
% %           [MeasuresNow(26)],...
% %           [MeasuresNow(27)],'r*','LineWidth',2)
% %     plot3([MeasuresNow(28)],...
% %           [MeasuresNow(29)],...
% %           [MeasuresNow(30)],'g*','LineWidth',2)
% %     plot3([MeasuresNow(31)],...
% %           [MeasuresNow(32)],...
% %           [MeasuresNow(33)],'b*','LineWidth',2)
% %     plot3([MeasuresNow(34)],...
% %           [MeasuresNow(35)],...
% %           [MeasuresNow(36)],'k*','LineWidth',2) 
% % 
% %     plot3([MeasuresNow(25) MeasuresNow(28) MeasuresNow(31) MeasuresNow(34) MeasuresNow(25)],...
% %           [MeasuresNow(26) MeasuresNow(29) MeasuresNow(32) MeasuresNow(35) MeasuresNow(26)],...
% %           [MeasuresNow(27) MeasuresNow(30) MeasuresNow(33) MeasuresNow(36) MeasuresNow(27)],'k-','LineWidth',2)
%     %%%%%%%%%%%%% MEASURED Positions of Markers HAND %%%%%%%%%%%%%%%%%%%%%%
% %     plot3([MeasuresNow(37)],...
% %           [MeasuresNow(38)],...
% %           [MeasuresNow(39)],'r*','LineWidth',2)
% %     plot3([MeasuresNow(40)],...
% %           [MeasuresNow(41)],...
% %           [MeasuresNow(42)],'g*','LineWidth',2)
% %     plot3([MeasuresNow(43)],...
% %           [MeasuresNow(44)],...
% %           [MeasuresNow(45)],'b*','LineWidth',2)
% %     plot3([MeasuresNow(46)],...
% %           [MeasuresNow(47)],...
% %           [MeasuresNow(48)],'k*','LineWidth',2)
% %     plot3([MeasuresNow(37) MeasuresNow(40) MeasuresNow(43) MeasuresNow(46) MeasuresNow(37)],...
% %           [MeasuresNow(38) MeasuresNow(41) MeasuresNow(44) MeasuresNow(47) MeasuresNow(38)],...
% %           [MeasuresNow(39) MeasuresNow(42) MeasuresNow(45) MeasuresNow(48) MeasuresNow(39)],'k-','LineWidth',2)
% % 

MeasuresNow = MKPosSmoothed(i,:)'; %column vector 48 elem
MeasuresNow = [StarLocalCoords(1,:)'; StarLocalCoords(2,:)'; StarLocalCoords(3,:)'; StarLocalCoords(4,:)'; MeasuresNow];  

%%%%%%%%%%%%%% MEASURED Positions of Markers ARM %%%%%%%%%%%%%%%%%%%%%%
    plot3([MeasuresNow(13)],...
          [MeasuresNow(14)],...
          [MeasuresNow(15)],'ro','LineWidth',2)
    plot3([MeasuresNow(16)],...
          [MeasuresNow(17)],...
          [MeasuresNow(18)],'go','LineWidth',2)
    plot3([MeasuresNow(19)],...
          [MeasuresNow(20)],...
          [MeasuresNow(21)],'bo','LineWidth',2)
    plot3([MeasuresNow(22)],...
          [MeasuresNow(23)],...
          [MeasuresNow(24)],'ko','LineWidth',2)

    plot3([MeasuresNow(13) MeasuresNow(16) MeasuresNow(19) MeasuresNow(22) MeasuresNow(13)],...
          [MeasuresNow(14) MeasuresNow(17) MeasuresNow(20) MeasuresNow(23) MeasuresNow(14)],...
          [MeasuresNow(15) MeasuresNow(18) MeasuresNow(21) MeasuresNow(24) MeasuresNow(15)],'g-','LineWidth',2)
    %%%%%%%%%%%% MEASURED Positions of Markers FOREARM %%%%%%%%%%%%%%%%%%%%
% %     plot3([MeasuresNow(25)],...
% %           [MeasuresNow(26)],...
% %           [MeasuresNow(27)],'ro','LineWidth',2)
% %     plot3([MeasuresNow(28)],...
% %           [MeasuresNow(29)],...
% %           [MeasuresNow(30)],'go','LineWidth',2)
% %     plot3([MeasuresNow(31)],...
% %           [MeasuresNow(32)],...
% %           [MeasuresNow(33)],'bo','LineWidth',2)
% %     plot3([MeasuresNow(34)],...
% %           [MeasuresNow(35)],...
% %           [MeasuresNow(36)],'ko','LineWidth',2) 
% %     plot3([MeasuresNow(25) MeasuresNow(28) MeasuresNow(31) MeasuresNow(34) MeasuresNow(25)],...
% %           [MeasuresNow(26) MeasuresNow(29) MeasuresNow(32) MeasuresNow(35) MeasuresNow(26)],...
% %           [MeasuresNow(27) MeasuresNow(30) MeasuresNow(33) MeasuresNow(36) MeasuresNow(27)],'g-','LineWidth',2)
%     %%%%%%%%%%%%% MEASURED Positions of Markers HAND %%%%%%%%%%%%%%%%%%%%%%
% %     plot3([MeasuresNow(37)],...
% %           [MeasuresNow(38)],...
% %           [MeasuresNow(39)],'ro','LineWidth',2)
% %     plot3([MeasuresNow(40)],...
% %           [MeasuresNow(41)],...
% %           [MeasuresNow(42)],'go','LineWidth',2)
% %     plot3([MeasuresNow(43)],...
% %           [MeasuresNow(44)],...
% %           [MeasuresNow(45)],'bo','LineWidth',2)
% %     plot3([MeasuresNow(46)],...
% %           [MeasuresNow(47)],...
% %           [MeasuresNow(48)],'ko','LineWidth',2)
% %     plot3([MeasuresNow(37) MeasuresNow(40) MeasuresNow(43) MeasuresNow(46) MeasuresNow(37)],...
% %           [MeasuresNow(38) MeasuresNow(41) MeasuresNow(44) MeasuresNow(47) MeasuresNow(38)],...
% %           [MeasuresNow(39) MeasuresNow(42) MeasuresNow(45) MeasuresNow(48) MeasuresNow(39)],'g-','LineWidth',2) 



    %%%%%%%%%%%% ESTIMATED Positions of Markers ARM %%%%%%%%%%%%%%%%%%%%%%%
% x = [DistWorldShoulder(1) DistWorldShoulder(1)      DistWorldShoulder(1)     DistWorldShoulder(1)];
% y = [DistWorldShoulder(2) DistWorldShoulder(2)-400  DistWorldShoulder(2)-400 DistWorldShoulder(2)];
% z = [DistWorldShoulder(3) DistWorldShoulder(3)      DistWorldShoulder(3)-100 DistWorldShoulder(3)-100];
% fill3(x,y,z,'yellow')
% 
% x = [DistWorldShoulder(1) DistWorldShoulder(1)-600  DistWorldShoulder(1)-600 DistWorldShoulder(1)];
% y = [DistWorldShoulder(2) DistWorldShoulder(2)      DistWorldShoulder(2)     DistWorldShoulder(2)];
% z = [DistWorldShoulder(3) DistWorldShoulder(3)      DistWorldShoulder(3)-100 DistWorldShoulder(3)-100];
% fill3(x,y,z,'yellow')
% 
% x = [DistWorldShoulder(1) DistWorldShoulder(1)      DistWorldShoulder(1)-600 DistWorldShoulder(1)-600];
% y = [DistWorldShoulder(2) DistWorldShoulder(2)-400  DistWorldShoulder(2)-400 DistWorldShoulder(2)];
% z = [DistWorldShoulder(3) DistWorldShoulder(3)      DistWorldShoulder(3)     DistWorldShoulder(3)];
% fill3(x,y,z,'yellow')


%axis( [-500 500 -200 300 -100 500])
axis equal
%view(88.000, -15.6)

xlabel x; ylabel y; zlabel z;

drawnow
 disp (['Exported ' mat2str(i) ' of ' mat2str(NumFrame)])
end
%close (v);
